# Generated by Django 5.1.1 on 2024-09-22 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('questao1', models.TimeField()),
                ('questao2', models.IntegerField()),
                ('questao3', models.TimeField()),
                ('questao4', models.IntegerField()),
                ('questao5a', models.IntegerField()),
                ('questao5b', models.IntegerField()),
                ('questao5c', models.IntegerField()),
                ('questao5d', models.IntegerField()),
                ('questao5e', models.IntegerField()),
                ('questao5f', models.IntegerField()),
                ('questao5g', models.IntegerField()),
                ('questao5h', models.IntegerField()),
                ('questao5i', models.IntegerField()),
                ('questao5j1', models.CharField(max_length=300)),
                ('questao5j2', models.IntegerField()),
                ('questao6', models.IntegerField()),
                ('questao7', models.IntegerField()),
                ('questao8', models.IntegerField()),
                ('questao9', models.IntegerField()),
                ('questao10', models.IntegerField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resultado', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
